name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Load .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_APP_KEY: DATABASE_URL
        envkey_APP_SECRET: postgresql://mars:1005@161.35.15.35/adspay
        file_name: .env
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 161.35.15.35
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/adspay-backend
          git pull
          uvicorn main:app --port=8001
